name: Robot Tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install backend dependencies (incluindo Flask)
        run: |
          python -m pip install --upgrade pip
          pip install flask

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install selenium webdriver-manager

      - name: Start Flask app in background
        run: |
          export FLASK_APP=app.py   
          nohup python -m flask run --host=0.0.0.0 --port=5000 &
      
      - name: Wait for Flask server to start
        run: sleep 5
          
      - name: Run Robot Framework tests
        run: |
          python robot_run.py

      - name: Upload Robot Framework output files
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: |
            output.xml
            report.html
            log.html
